// FILE: QRScannerPairingValidator.swift
// Purpose: Classifies scanned or pasted pairing payloads so the pairing flow can block outdated computer bridges before reconnecting.
// Layer: View support
// Exports: validatePairingQRCode
// Depends on: Foundation, CodexPairingQRPayload, CodexBridgeUpdatePrompt

import Foundation

enum QRScannerPairingValidationResult {
    case success(CodexPairingQRPayload)
    case shortCode(String)
    case scanError(String)
    case bridgeUpdateRequired(CodexBridgeUpdatePrompt)
}

private let qrScannerPairingCodePrefix = "RMX1:"
private let trifectaPairingDeviceId = "trifecta-desktop"
private let trifectaPairingIdentityKey = "trifecta-desktop-effect-rpc"
private let qrScannerShortCodePattern = "^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{8,12}$"

// Distinguishes a usable pairing QR from stale bridge payloads and generic camera mis-scans.
func validatePairingQRCode(_ code: String, now: Date = Date()) -> QRScannerPairingValidationResult {
    let trimmedCode = code.trimmingCharacters(in: .whitespacesAndNewlines)
    let normalizedShortCode = trimmedCode
        .uppercased()
        .replacingOccurrences(of: "-", with: "")
        .replacingOccurrences(of: " ", with: "")
    if normalizedShortCode.range(of: qrScannerShortCodePattern, options: .regularExpression) != nil {
        return .shortCode(normalizedShortCode)
    }

    if let payload = makeTrifectaPairingPayload(from: trimmedCode) {
        return .success(payload)
    }

    let normalizedCode: String
    if trimmedCode.hasPrefix(qrScannerPairingCodePrefix) {
        guard let decodedCode = decodePairingCode(trimmedCode) else {
            return .scanError("This pairing code is unreadable. Copy it again from the computer bridge.")
        }
        normalizedCode = decodedCode
    } else {
        normalizedCode = trimmedCode
    }

    guard let data = normalizedCode.data(using: .utf8) else {
        return .scanError("Pairing code contains invalid text encoding.")
    }

    let decoder = JSONDecoder()
    if let payload = try? decoder.decode(CodexPairingQRPayload.self, from: data) {
        guard payload.v == codexPairingQRVersion else {
            return .scanError("This QR code was generated by a different Trifecta version. Generate a fresh pairing code from Trifecta Desktop.")
        }

        guard !payload.relay.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .scanError("Pairing code is missing the relay URL. Re-generate it from the bridge.")
        }

        guard !payload.sessionId.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .scanError("Pairing code is missing the session ID. Re-generate it from the bridge.")
        }

        let expiryDate = Date(timeIntervalSince1970: TimeInterval(payload.expiresAt) / 1000)
        guard expiryDate.addingTimeInterval(codexSecureClockSkewToleranceSeconds) >= now else {
            return .scanError("This pairing code has expired. Generate a new one from the computer bridge.")
        }

        return .success(payload)
    }

    if looksLikeTrifectaPairingPayload(data) {
        return .scanError("This QR code is from an old pairing format. Generate a fresh pairing code from Trifecta Desktop.")
    }

    return .scanError("Not a valid secure pairing code. Make sure you're scanning a QR from the latest Trifecta bridge.")
}

func isTrifectaPairingPayload(_ payload: CodexPairingQRPayload) -> Bool {
    payload.macDeviceId == trifectaPairingDeviceId
        && payload.macIdentityPublicKey == trifectaPairingIdentityKey
}

func makeTrifectaPairingPayload(serverURL: String, token: String) -> CodexPairingQRPayload {
    CodexPairingQRPayload(
        v: codexPairingQRVersion,
        relay: serverURL,
        sessionId: token,
        macDeviceId: trifectaPairingDeviceId,
        macIdentityPublicKey: trifectaPairingIdentityKey,
        expiresAt: Int64(Date().addingTimeInterval(24 * 60 * 60).timeIntervalSince1970 * 1000)
    )
}

private func makeTrifectaPairingPayload(from rawCode: String) -> CodexPairingQRPayload? {
    guard let parsed = parseTrifectaPairingURL(rawCode) else {
        return nil
    }

    return CodexPairingQRPayload(
        v: codexPairingQRVersion,
        relay: parsed.serverURL,
        sessionId: parsed.token,
        macDeviceId: trifectaPairingDeviceId,
        macIdentityPublicKey: trifectaPairingIdentityKey,
        expiresAt: Int64(Date().addingTimeInterval(24 * 60 * 60).timeIntervalSince1970 * 1000)
    )
}

private func parseTrifectaPairingURL(_ rawCode: String) -> (serverURL: String, token: String)? {
    let trimmed = rawCode.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty, let components = URLComponents(string: trimmed) else {
        return nil
    }

    if let host = components.queryItems?.first(where: { $0.name == "host" })?.value,
       let token = trifectaToken(from: components),
       let serverURL = normalizedTrifectaServerURL(host) {
        return (serverURL.absoluteString, token)
    }

    guard let token = trifectaToken(from: components),
          let scheme = components.scheme,
          let host = components.host else {
        return nil
    }

    var direct = URLComponents()
    direct.scheme = scheme
    direct.host = host
    direct.port = components.port
    guard let url = direct.url.flatMap(normalizedTrifectaServerURL) else {
        return nil
    }

    return (url.absoluteString, token)
}

private func trifectaToken(from components: URLComponents) -> String? {
    if let fragment = components.fragment,
       let fragmentComponents = URLComponents(string: "?\(fragment)"),
       let token = fragmentComponents.queryItems?.first(where: { $0.name == "token" })?.value?
        .trimmingCharacters(in: .whitespacesAndNewlines),
       !token.isEmpty {
        return token
    }

    guard let token = components.queryItems?.first(where: { $0.name == "token" })?.value?
        .trimmingCharacters(in: .whitespacesAndNewlines),
          !token.isEmpty else {
        return nil
    }
    return token
}

private func normalizedTrifectaServerURL(_ raw: String) -> URL? {
    guard let url = URL(string: raw) else {
        return nil
    }
    return normalizedTrifectaServerURL(url)
}

private func normalizedTrifectaServerURL(_ url: URL) -> URL? {
    guard var components = URLComponents(url: url, resolvingAgainstBaseURL: false) else {
        return nil
    }
    guard ["http", "https", "ws", "wss"].contains(components.scheme?.lowercased() ?? "") else {
        return nil
    }
    if components.scheme == "ws" {
        components.scheme = "http"
    } else if components.scheme == "wss" {
        components.scheme = "https"
    }
    components.path = ""
    components.query = nil
    components.fragment = nil
    return components.url
}

// Reuses the QR validator for manual entry by decoding the bridge's paste-friendly token back into JSON.
private func decodePairingCode(_ code: String) -> String? {
    let encoded = String(code.dropFirst(qrScannerPairingCodePrefix.count))
        .replacingOccurrences(of: "-", with: "+")
        .replacingOccurrences(of: "_", with: "/")
    let paddingCount = (4 - (encoded.count % 4)) % 4
    let padded = encoded + String(repeating: "=", count: paddingCount)
    guard let data = Data(base64Encoded: padded) else {
        return nil
    }
    return String(data: data, encoding: .utf8)
}

private func looksLikeTrifectaPairingPayload(_ data: Data) -> Bool {
    guard let jsonObject = try? JSONSerialization.jsonObject(with: data),
          let object = jsonObject as? [String: Any] else {
        return false
    }

    let pairingKeys: Set<String> = [
        "relay",
        "sessionId",
        "macDeviceId",
        "macIdentityPublicKey",
        "expiresAt",
        "v",
    ]
    return !pairingKeys.isDisjoint(with: object.keys)
}

private func makeScannerBridgeUpdatePrompt(message: String) -> CodexBridgeUpdatePrompt {
    CodexBridgeUpdatePrompt(
        title: "Update Trifecta on your computer before scanning",
        message: message,
        command: nil
    )
}
